import type {
  StyleBlock,
  StyleRule,
  VariantDeclaration,
  ResponsiveBlock,
  TokenRegistry,
  StyleResult,
  VariantStyle,
  ResponsiveStyle,
  CSSRule,
  TokenReference,
} from '@drift/types'
import { generateScopedClassName } from './scoping'

/**
 * Extract styles from a component's style block
 */
export function extractStyles(
  componentName: string,
  styleBlock: StyleBlock,
  tokenRegistry?: TokenRegistry,
  breakpoints?: Record<string, number>
): StyleResult {
  const scopedClassName = generateScopedClassName(componentName)
  
  // Extract base styles
  const baseStyles = styleBlock.base.flatMap((rule) =>
    convertStyleRule(rule, tokenRegistry)
  )

  // Extract variant styles
  const variants = styleBlock.variants.map((variant) =>
    extractVariant(componentName, variant, tokenRegistry)
  )

  // Extract responsive styles with breakpoint values
  const responsive = styleBlock.responsive.map((block) =>
    extractResponsive(componentName, block, tokenRegistry, breakpoints)
  )

  return {
    componentName,
    scopedClassName,
    baseStyles,
    variants,
    responsive,
    cssOutput: '', // Will be generated by CSS generator
  }
}

/**
 * Convert a style rule to a CSS rule
 */
function convertStyleRule(
  rule: StyleRule,
  tokenRegistry?: TokenRegistry
): CSSRule[] {
  let value: string

  if (typeof rule.value === 'string') {
    value = rule.value
  } else {
    // Token reference
    const tokenRef = rule.value as TokenReference
    const tokenPath = tokenRef.path.join('.')
    
    if (tokenRegistry) {
      // Resolve token reference
      value = `$${tokenPath}` // Placeholder, will be resolved by token resolver
    } else {
      value = `var(--${tokenPath.replace(/\./g, '-')})`
    }
  }

  value = normalizeStyleValue(value)

  // Resolve inline token references in compound values like "$space.3 $space.6".
  value = value.replace(/\$([a-zA-Z][a-zA-Z0-9.]*)/g, (match) => {
    return `var(--${match.substring(1).replace(/\./g, '-')})`
  })

  return expandShorthand(rule.property, value).map((expandedRule) => ({
    ...expandedRule,
    important: rule.important || expandedRule.important,
  }))
}

/**
 * Convert Drift property names to CSS property names
 */
function convertPropertyName(property: string): string {
  const propertyMap: Record<string, string> = {
    bg: 'background',
    border: 'border',
    h: 'height',
    maxH: 'max-height',
    maxW: 'max-width',
    minH: 'min-height',
    minW: 'min-width',
    pad: 'padding',
    radius: 'border-radius',
    shadow: 'box-shadow',
    text: 'color',
    w: 'width',
  }

  return propertyMap[property] || property
}

function normalizeStyleValue(value: string): string {
  return value
    .replace(/\s*\(\s*/g, '(')
    .replace(/\s*\)\s*/g, ')')
    .replace(/\s*,\s*/g, ', ')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Extract variant styles
 */
function extractVariant(
  _componentName: string,
  variant: VariantDeclaration,
  tokenRegistry?: TokenRegistry
): VariantStyle {
  const values = new Map<string, CSSRule[]>()

  variant.values.forEach((value) => {
    const rules = value.styles.flatMap((rule) =>
      convertStyleRule(rule, tokenRegistry)
    )
    values.set(value.name, rules)
  })

  return {
    name: variant.name,
    values,
    defaultValue: variant.defaultValue,
  }
}

/**
 * Apply default variant values when not specified
 */
export function applyDefaultVariants(
  styleResult: StyleResult,
  appliedVariants: Record<string, string>
): string[] {
  const classNames: string[] = [styleResult.scopedClassName]

  styleResult.variants.forEach((variant) => {
    const appliedValue = appliedVariants[variant.name]
    const valueToUse = appliedValue || variant.defaultValue

    if (valueToUse && variant.values.has(valueToUse)) {
      classNames.push(
        `${styleResult.scopedClassName}--${variant.name}-${valueToUse}`
      )
    }
  })

  return classNames
}

/**
 * Extract responsive styles
 */
function extractResponsive(
  _componentName: string,
  block: ResponsiveBlock,
  tokenRegistry?: TokenRegistry,
  breakpoints?: Record<string, number>
): ResponsiveStyle {
  const rules = block.styles.flatMap((rule) =>
    convertStyleRule(rule, tokenRegistry)
  )

  // Get breakpoint value from config or use defaults
  const defaultBreakpoints: Record<string, number> = {
    sm: 640,
    md: 768,
    lg: 1024,
    xl: 1280,
    '2xl': 1536,
    // Legacy names
    mobile: 640,
    tablet: 768,
    desktop: 1024,
  }

  const allBreakpoints = { ...defaultBreakpoints, ...breakpoints }

  return {
    breakpoint: block.breakpoint,
    minWidth: allBreakpoints[block.breakpoint] || 0,
    rules,
  }
}

/**
 * Expand shorthand properties
 */
export function expandShorthand(property: string, value: string): CSSRule[] {
  // Handle layout shorthands
  if (property === 'layout') {
    return expandLayoutShorthand(value)
  }

  // Handle padding/margin shorthands
  if (property === 'pad' || property === 'padding') {
    return expandSpacingShorthand('padding', value)
  }

  if (property === 'p' || property === 'px' || property === 'py' || property === 'pt' || property === 'pr' || property === 'pb' || property === 'pl') {
    return expandDirectionalSpacing('padding', property, value)
  }

  if (property === 'margin' || property === 'm') {
    return expandSpacingShorthand('margin', value)
  }

  if (property === 'mx' || property === 'my' || property === 'mt' || property === 'mr' || property === 'mb' || property === 'ml') {
    return expandDirectionalSpacing('margin', property, value)
  }

  if (property === 'size') {
    return [
      { property: 'width', value, important: false },
      { property: 'height', value, important: false },
    ]
  }

  if (property === 'border') {
    return expandBorderShorthand(value)
  }

  if (property === 'shadow') {
    return [{ property: 'box-shadow', value: expandShadowValue(value), important: false }]
  }

  // Single property
  return [
    {
      property: convertPropertyName(property),
      value,
      important: false,
    },
  ]
}

/**
 * Expand layout shorthand (row, col, grid, center, stack)
 */
function expandLayoutShorthand(value: string): CSSRule[] {
  const parts = value.split(/\s+/)
  const rules: CSSRule[] = []

  parts.forEach((part) => {
    switch (part) {
      case 'row':
        rules.push(
          { property: 'display', value: 'flex', important: false },
          { property: 'flex-direction', value: 'row', important: false }
        )
        break
      case 'col':
        rules.push(
          { property: 'display', value: 'flex', important: false },
          { property: 'flex-direction', value: 'column', important: false }
        )
        break
      case 'center':
        rules.push(
          { property: 'align-items', value: 'center', important: false },
          { property: 'justify-content', value: 'center', important: false }
        )
        break
      case 'v-center':
        rules.push({ property: 'align-items', value: 'center', important: false })
        break
      case 'h-center':
        rules.push({ property: 'justify-content', value: 'center', important: false })
        break
      case 'between':
        rules.push({ property: 'justify-content', value: 'space-between', important: false })
        break
      case 'around':
        rules.push({ property: 'justify-content', value: 'space-around', important: false })
        break
      case 'evenly':
        rules.push({ property: 'justify-content', value: 'space-evenly', important: false })
        break
      case 'wrap':
        rules.push({ property: 'flex-wrap', value: 'wrap', important: false })
        break
      case 'no-wrap':
        rules.push({ property: 'flex-wrap', value: 'nowrap', important: false })
        break
      case 'stack':
        rules.push({ property: 'position', value: 'relative', important: false })
        break
      case 'inline':
        rules.push({ property: 'display', value: 'inline-flex', important: false })
        break
      case 'block':
        rules.push({ property: 'display', value: 'block', important: false })
        break
      default:
        // Handle grid(N) syntax
        if (part.startsWith('grid(')) {
          const cols = part.match(/grid\((\d+)\)/)?.[1]
          if (cols) {
            rules.push(
              { property: 'display', value: 'grid', important: false },
              {
                property: 'grid-template-columns',
                value: `repeat(${cols}, 1fr)`,
                important: false,
              }
            )
          }
        } else if (part.startsWith('gap(')) {
          const gap = part.slice(4, -1)
          if (gap) {
            rules.push({ property: 'gap', value: gap, important: false })
          }
        }
    }
  })

  return rules
}

function expandDirectionalSpacing(property: 'padding' | 'margin', shorthand: string, value: string): CSSRule[] {
  const direction = shorthand.replace(/^p|^m/, '')

  switch (direction) {
    case '':
      return expandSpacingShorthand(property, value)
    case 'x':
      return [
        { property: `${property}-left`, value, important: false },
        { property: `${property}-right`, value, important: false },
      ]
    case 'y':
      return [
        { property: `${property}-top`, value, important: false },
        { property: `${property}-bottom`, value, important: false },
      ]
    case 't':
      return [{ property: `${property}-top`, value, important: false }]
    case 'r':
      return [{ property: `${property}-right`, value, important: false }]
    case 'b':
      return [{ property: `${property}-bottom`, value, important: false }]
    case 'l':
      return [{ property: `${property}-left`, value, important: false }]
    default:
      return [{ property, value, important: false }]
  }
}

function expandBorderShorthand(value: string): CSSRule[] {
  if (value === 'none') {
    return [{ property: 'border', value: 'none', important: false }]
  }

  if (value.startsWith('color(') && value.endsWith(')')) {
    return [{ property: 'border-color', value: value.slice(6, -1), important: false }]
  }

  if (value.startsWith('width(') && value.endsWith(')')) {
    return [{ property: 'border-width', value: value.slice(6, -1), important: false }]
  }

  return [{ property: 'border', value, important: false }]
}

function expandShadowValue(value: string): string {
  const shadows: Record<string, string> = {
    none: 'none',
    sm: '0 1px 2px rgb(15 23 42 / 0.08)',
    md: '0 8px 24px rgb(15 23 42 / 0.12)',
    lg: '0 18px 48px rgb(15 23 42 / 0.16)',
    focus: '0 0 0 3px rgb(59 130 246 / 0.35)',
  }

  return shadows[value] || value
}

/**
 * Expand spacing shorthand (padding, margin)
 */
function expandSpacingShorthand(property: string, value: string): CSSRule[] {
  const parts = value.split(/\s+/)

  if (parts.length === 1) {
    return [{ property, value: parts[0] ?? '', important: false }]
  }

  if (parts.length === 2) {
    return [
      { property: `${property}-top`, value: parts[0] ?? '', important: false },
      { property: `${property}-right`, value: parts[1] ?? '', important: false },
      { property: `${property}-bottom`, value: parts[0] ?? '', important: false },
      { property: `${property}-left`, value: parts[1] ?? '', important: false },
    ]
  }

  if (parts.length === 4) {
    return [
      { property: `${property}-top`, value: parts[0] ?? '', important: false },
      { property: `${property}-right`, value: parts[1] ?? '', important: false },
      { property: `${property}-bottom`, value: parts[2] ?? '', important: false },
      { property: `${property}-left`, value: parts[3] ?? '', important: false },
    ]
  }

  return [{ property, value, important: false }]
}
